version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
      container_name: docker-fastapi
      build: .
      ports:
        - '8000:8000'
      depends_on:
        - postgres
      restart:
        always

volumes:
  postgres-data: